server:
  port: ${SERVER_PORT:8080}
  url: ${SERVER_URL:}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/${DATASOURCE_DATABASE:library}?useSSL=false&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:QuanNM_0516}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true